name: FageBoot

on:
  workflow_dispatch:
    inputs:
      type:
        description: Tipo de módulo
        type: choice
        options: [page, component]
        default: page
        required: true
      name:
        description: Nombre visible (sin tildes se limpian)
        required: true
      desc:
        description: Descripción (opcional)
        required: false

permissions:
  contents: write
  pull-requests: write

jobs:
  gen:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Ejecuta FageBoot con los parámetros ingresados
      - name: Run FageBoot
        run: |
          node bin/fageboot.mjs "${{ github.event.inputs.type }}" "${{ github.event.inputs.name }}" --desc "${{ github.event.inputs.desc }}"

      # Crea PR con los cambios (rama nueva automática)
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          branch: fb/${{ github.event.inputs.type }}-${{ github.event.inputs.name }}
          title: "FageBoot: add ${{ github.event.inputs.type }} — ${{ github.event.inputs.name }}"
          commit-message: "chore(fageboot): ${{ github.event.inputs.type }} ${{ github.event.inputs.name }}"
          body: |
            Generated by FageBoot.
            - type: ${{ github.event.inputs.type }}
            - name: ${{ github.event.inputs.name }}
            - desc: ${{ github.event.inputs.desc }}
          labels: fageboot
