name: FageBoot

on:
  workflow_dispatch:  # <-- esto habilita el botón "Ejecutar flujo de trabajo"

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Hola
        run: echo "FageBoot listo"
