name: FageBoot

on:
  workflow_dispatch:
    inputs:
      type:
        description: "Tipo de módulo"
        type: choice
        options: [page, component]
        default: page
        required: true
      name:
        description: "Nombre visible (sin tildes se limpian)"
        required: true
      description:
        description: "Descripción (opcional)"
        required: false

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      # (Opcional) si tu repo usa paquetes, instala:
      - name: Install deps (if any)
        run: |
          if [ -f package-lock.json ] || [ -f pnpm-lock.yaml ] || [ -f yarn.lock ]; then
            npm ci || true
          fi

      # Genera un módulo sencillito en origen/modulos/<slug>/index.html
      - name: Generate module files
        run: |
          node - <<'NODE'
          const fs = require('fs'), path = require('path');
          const type = process.env.INPUT_TYPE || 'page';
          const name = process.env.INPUT_NAME || 'demo';
          const desc = process.env.INPUT_DESCRIPTION || '';

          // slug: quita tildes y espacios → guiones
          const slug = name.normalize('NFD')
            .replace(/[\u0300-\u036f]/g,'')
            .replace(/[^a-zA-Z0-9]+/g,'-')
            .replace(/^-|-$/g,'')
            .toLowerCase();

          // Carpeta destino (evitamos acentos para no liarnos)
          const base = path.join('origen', 'modulos', slug);
          fs.mkdirSync(base, { recursive: true });

          const html = `<!doctype html>
<meta charset="utf-8">
<title>${name}</title>
<h1>${name}</h1>
<p>${desc}</p>
<p>Tipo: ${type}</p>
`;

          fs.writeFileSync(path.join(base, 'index.html'), html);
          console.log('Generated at:', base);
          NODE
        env:
          INPUT_TYPE: ${{ github.event.inputs.type }}
          INPUT_NAME: ${{ github.event.inputs.name }}
          INPUT_DESCRIPTION: ${{ github.event.inputs.description }}

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "feat(fageboot): add ${{ github.event.inputs.type }}: ${{ github.event.inputs.name }}" || echo "No changes"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          branch: chore/fageboot-${{ github.event.inputs.type }}-${{ github.event.inputs.name }}
          title: "FageBoot: ${{ github.event.inputs.type }} — ${{ github.event.inputs.name }}"
          body: ${{ github.event.inputs.description || 'Auto-generado por FageBoot' }}
          labels: |
            fageboot
            automated
